config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    get "signup" => "devise/registrations#new"
    post "signup" => "devise/registrations#create"
  end
  root 'homepages#home'
  get 'home', to: 'homepages#home'
  resources :users, only: :show
  resources :password_resets, only: [:new, :create, :edit,:update]
end 
  root 'homepages#home'
  namespace :admin do
    get 'home', to: 'homepages#index'
    resources :categories do 
      resources :products
    end
    resources :products, only: [:index]
    resources :toppings, except: [:update, :edit, :show]
    resources :orders, only: [:index]
  end


  resources :categories, only: [:index, :show] do 
    resources :products, only: [:index , :show]
  end

  devise_for :users
  as :user do  
    get 'login', to: 'devise/sessions#new'
    post 'signup' , to: 'devise/registrations#create'
    get 'signup', to: 'devise/registrations#new'
    get 'edit', to: 'devise/registrations#edit'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  resources :products, only:[:index]
  resources :products, only:[:show] do
    resources :comments , only:[:index, :create]
  end
  resources :toppings, only:[:index]
  resources :users, except:[:destroy, :index] do
    resources :comments, only:[:create, :destroy]
  end 
  resources :users, only:[:show] do
    resources :addresses
  end
  resources :carts, only:[:create, :index]
  resources :cart_items, only:[:create, :update, :destroy]
  resources :orders ,except:[:edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homepages_controller.rb
class Admin::HomepagesController < Admin::BaseController
  def index
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
    def home
     end 
  def home
    @categories = Category.all
    @products = Product.all
    @carts = current_cart
    if signed_in?
      @addresses = current_user.addresses
    end
  end
end

app/helpers/admin/homepages_helper.rb
module Admin::HomepagesHelper
end

app/views/homepages/_product.html.erb
<div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
  <div class="all-meal">
    <div class="top">
      <%= link_to category_product_path(product.category.id,product) do %>
        <div class="bg-gradient"></div>
      <% end %>
      <div class="top-img">
        <%= link_to category_product_path(product.category.id,product) do %>
          <%= image_tag product.images.first %>
        <% end %>
      </div>
      <div class="logo-img">
        <%= image_tag product.category.image %>
      </div>
      <div class="top-text">
        <div class="heading">
          <h4>
            <%= link_to category_product_path(product.category.id,product) do %>
              <%= product.name_product%>
            <% end %>
          </h4>
        </div>
        <div class="sub-heading">
          <h5>
            <%= link_to "#" do %>
              <%= product.category.name%>
            <% end %>
          </h5>
          <p></p>
        </div>
      </div>
    </div>
    <div class="bottom">
      <div class="bottom-text">
        <div class="delivery"><i class="fas fa-shopping-cart"></i>Delivery Free : Free</div>
        <div class="time"><i class="far fa-clock"></i>Delivery Time : 30 Min</div>
        <div class="star">
          Rating
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homepages/home.html.erb
<% if user_signed_in? %>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Account </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown"> 
            <%= link_to "Profile", current_user, class:"dropdown-item"%>
            <%= link_to "Setting", edit_user_registration_path, class:"dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path,class:"dropdown-item", :method => :delete %>
        </div>
    </li> 
    <% else %>
    <li class="form-group">   
        <a class="nav-link content="width=device-width, initial-scale=1" <%= link_to "Log in", signin_path %> </a>
        <a class="nav-link content="width=device-width, initial-scale=1" <%= link_to "Sign Up", new_user_registration_path %> </a>
    </li>
<% end %> 

<section class="block-preview">
  <div class="cover-banner" style="background-image: url(https://images3.alphacoders.com/922/922680.jpg)"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-6 col-sm-12">
        <div class="left-text-b">
          <h1 class="title"><%= t ".title"%></h1>
          <h6 class="exeption"><%= t ".exeption"%></h6>
          <p>Get our services from 24 hours.</p>
          <a class="bnr-btn btn-link" href="#"><%= t ".gotomail"%></a>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
        <form>
          <div class="form-box">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-map-marker-alt"></i></div>
            </div>
            <input class="find-address skills" name="search" type="text" placeholder="Choose your food " />
            <div class="input-group-prepend">
              <div class="input-group-text-1"><i class="fas fa-utensils"></i></div>
            </div>
            <input class="find-resto skills" name="search" type="text" placeholder="Choose your drinks" />
            <input class="find-address skills" name="search" type="text" placeholder="Choose your location" />
            <div class="input-group-prepend">
              <div class="input-group-text-1"><i class="fas fa-utensils"></i></div>
            </div>
            <input class="find-resto skills" name="search" type="text" placeholder="Choose restaurant" />
            <button class="search-btn btn-link" type="button">Find Food</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<section class="browse-places">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3> Browse Places </h3>
      </div>
    </div>
  </div>
  <div class="container items">
    <div class="row">
      <div class="col-md-2">
        <div class="owl-carousel">
          <div class="item">
            <%= image_tag 'brower_coffee.png', class:'carousel-icon' %>
          </div>
          <div class="place">
            <h4>Coffee More</h4>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="owl-carousel">
          <div class="item">
            <%= image_tag 'brower_drink.png', class:'carousel-icon' %>
          </div>
          <div class="place">
            <h4>Drink & Nightkise</h4>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="owl-carousel">
          <div class="item">
            <%= image_tag 'brower_cake.png', class:'carousel-icon' %>
          </div>
          <div class="place">
            <h4>Desserts & Cakes</h4>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="owl-carousel">
          <div class="item">
            <%= image_tag 'brower_open.png', class:'carousel-icon' %>
          </div>
          <div class="place">
            <h4>Newly Opened</h4>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="owl-carousel">
          <div class="item">
            <%= image_tag 'brower_even.png', class:'carousel-icon' %>
          </div>
          <div class="place">
            <h4>Upcoming Event</h4>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <div class="owl-carousel">
          <div class="item">
            <%= image_tag 'brower_gps.png', class:'carousel-icon' %>
          </div>
          <div class="place">
            <h4>Near by</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--how-to-work start-->
<section class="how-to-work">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-12 col-xs-12">
        <div class="work-item">
        
          <div class="work-text">
            <h4>Choose Your Food </h4>
          <div class="work-img">
            <%= image_tag 'icon3.png' %>
          </div>
          <div class="work-text">
            <h4><%= t ".worktext1"%></h4>
            <p><%= t ".worktext2"%></p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-12 col-xs-12">
        <div class="work-item">
         <div class="work-text">
          <h4> Food</h4>
          <div class="work-img">
           <%= image_tag 'icon4.png' %>
         </div>
         <div class="work-text">
          <h4>Choose Food</h4>
          <p>Donec et tellus sed lorem condimentum maximus. Sed tempor, leo tempus condimentum.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
      <div class="work-item">
        <div class="work-img">
         <%= image_tag 'icon5.png' %>
       </div>
       <div class="work-text">
        <h4>Delivery</h4>
        <p>Donec et tellus sed lorem condimentum maximus. Sed tempor, leo tempus condimentum.</p>
      </div>
    </div>
  </div>
</section>
<section class="order-food-online">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="new-heading">
          <h1> Order Food Online In Your Area </h1>
        </div>
        <div class="your-location">
          <% if signed_in? %>
            <span><i class="fas fa-map-marker-alt"></i><%= @addresses.first.stress %></span>Change Location
          <% end %>
        </div>
        <div class="all-items">
          <div class="search col-lg-4 col-md-6 col-sm-12 col-xs-12">
            <form>
              <input class="search-location" name="search" type="search" placeholder="Enter Your Location" />
              <div class="icon-btn">
                <div class="cross-icon">
                  <i class="fas fa-crosshairs"></i>
                </div>
                <div class="s-m-btn">
                  <button class="search-meal-btn btn-link">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <% @products.each do |product|%>
        <%= render 'product', product: product %>
      <% end %>
      <div class="meal-btn">
        <a href="#" class="m-btn btn-link">Show All</a>
      </div>
    </div>
  </div>
</section>