config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    get "signup" => "devise/registrations#new"
    post "signup" => "devise/registrations#create"
  end
  root 'homepages#home'
  get 'home', to: 'homepages#home'
  resources :users, only: :show
  resources :password_resets, only: [:new, :create, :edit,:update]
end 
  root 'homepages#home'
  namespace :admin do
    get 'home', to: 'homepages#index'
    resources :categories do 
      resources :products
    end
    resources :products, only: [:index]
    resources :toppings, except: [:update, :edit, :show]
    resources :orders, only: [:index]
  end


  resources :categories, only: [:index, :show] do 
    resources :products, only: [:index , :show]
  end

  devise_for :users
  as :user do  
    get 'login', to: 'devise/sessions#new'
    post 'signup' , to: 'devise/registrations#create'
    get 'signup', to: 'devise/registrations#new'
    get 'edit', to: 'devise/registrations#edit'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  resources :products, only:[:index]
  resources :products, only:[:show] do
    resources :comments , only:[:index, :create]
  end
  resources :toppings, only:[:index]
  resources :users, except:[:destroy, :index] do
    resources :comments, only:[:create, :destroy]
  end 
  resources :users, only:[:show] do
    resources :addresses
  end
  resources :carts, only:[:create, :index]
  resources :cart_items, only:[:create, :update, :destroy]
  resources :orders ,except:[:edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items
  
  has_one :order


  def caculate_total_amount
    cart_items.collect do |ci|
      ci.valid? ? ci.quantity * ci.save_price_to_cart_item : 0
    end
  end
  def coupons
    a = self.caculate_total_amount.sum.to_f
    if a >= 100
      a * 10/100
    elsif a >= 80
      a * 5/100
    elsif a >= 35
      a * 2/100
    else
      a
    end
  end
  def total_price_after_coupons
    b = self.caculate_total_amount.sum.to_f - self.coupons
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_cart
    @cart_items = @cart.cart_items.includes(:product).order(created_at: :desc)
    @order = current_cart.order
  end
  def create
    
  end
  private
  def cart_params
    params.require(:cart).permit :total_amount
  end
end

app/views/carts/index.html.erb
<% if @cart_items.blank? %>
    <h3 style="text-align: center;">You haven't product in cart </h3>
<% else %>
  <div class="container">
    <h2 style="text-align: center; margin-bottom: 10px;">My Cart</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Product name</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
        <tr>
          <td> <%= image_tag(cart_item.product.images.first)%> </td>
          <td>
            <%= link_to cart_item.product.name_product, category_product_path(cart_item.product.category, cart_item.product) %>
          </td>
          <td class="buying">
            <div class="create-cart">
              <%= number_field_tag :quantity, cart_item.quantity , in: 1..99, step:1, 
               class:"form-control quantity", id:"cart_item_quantity-#{cart_item.id}"%>
            </div>
            <script>
              $("#cart_item_quantity-"+ <%=cart_item.id%>).change(function (){
                var quantity = $(this).val();
                $.ajax({
                  type: "patch",
                  url: "<%= cart_item_path(cart_item) %>",
                  data: {cart_item: {quantity: quantity}} ,
                  dataType: "script",
                })
              })
            </script>
          </td>
          <td id="cart-price-<%=cart_item.id%>" data-pricePr="<%=cart_item.product.price%>">
            $<%= cart_item.get_total_price %>
          </td>
          <td>
          <%= link_to cart_item_path(cart_item.id), remote:true, method: :delete, id:"delete-cart-item" do %>
            <%= image_tag 'remove.png',style:'width:20px'%>
          <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <hr/>
    <br/>
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <h4> Total the Bill: </h4> 
        </div>
        <div class="col-md-3">
          <h5 id="cart-total-amount">$<%= current_cart.caculate_total_amount.sum%></h5>
          <div class="order">
            <%= form_for current_cart, url: user_addresses_path(current_user.id), method: :get, class:"form-group" do |f| %>
              <%= f.hidden_field :cart_id, value: current_cart.id %>
              <%= f.submit "Go to order", class:"btn btn-origin" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>  